## Configuração Default da Aplicação ##

server:
  ## HTTP Server port
  port: ${eureka.port}

## Config Application
spring:
  application:
    name: vtswebapidiscovery

## Eureka - Service Discovery
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}/
