## Configuração Default da Aplicação ##

server:
  port: ${server.port}

## Eureka - Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}/
    register-with-eureka: true
    fetch-registry: true

## Config Application and Database
spring:
  application:
    name: vtswebapiestados
  datasource:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
  jpa:
    show-sql: false
    database-platform: ${spring.datasource.jpa.database-platform}
    properties:
      hibernate:
        ddl-auto: update
