## Configuração Default da Aplicação ##

server:
  host: ${server.host}
  port: ${server.port}

## Eureka - Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}/
    register-with-eureka: true
    healthcheck:
      enabled: true

## Config Application and Database
spring:
  application:
    name: vtswebapiestados
  datasource:
    url: ${database.url}
    password: ${database.password}
    username: ${database.username}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: ${database.minimum-idle}
      maximum-pool-size: ${database.maximum-pool-size}
      connectionTimeout: 180000
      idleTimeout: 60000
      maxLifetime: 180000
      ##leak-detection-threshold: 2000
  jpa:
    show-sql: false
    database-platform: ${database.database-platform}
    properties:
      hibernate:
        ddl-auto: update
