## Configuração do Ambiente do Cliente (Máquina na Hml) ##

server:
  port: 8082

# Config do service discovery
eureka:
  host: localhost
  name: eureka
  port: 8081

## Config Database
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/vtswebapi
    username: root
    password: vs368797

settings:
  allow-origin: 'http://localhost:8080/*'