server:
  host: 172.31.66.252
  port: 8082

# Config do service discovery
eureka:
  host: 172.31.66.252
  name: eureka
  port: 8084

## Config Database
spring:
  datasource:
    database-platform: org.hibernate.dialect.SQLServerDialect
    url: jdbc:sqlserver://localhost:1433;databaseName=vtswebapi;useBulkCopyForBatchInsert=true;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    minimum-idle: 10
    maximum-pool-size: 20