## Configuração Default da Aplicação ##

server:
  port: ${server.port}

## Eureka - Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}
    register-with-eureka: true
    fetch-registry: true

## Config Application and Database
spring:
  application:
    name: VTSWEBAPIGATEWAY
  cloud:
    gateway:
      routes:
        - id: VTSWEBAPIGATEWAY
          uri: lb://VTSWEBAPIGATEWAY
          predicates:
            - Path:/estados/**